#
# Copyright 2011-2025 Branimir Karadzic. All rights reserved.
# License: https://github.com/bkaradzic/bgfx/blob/master/LICENSE
#

BGFX_DIR=../../../external/bgfx
RUNTIME_DIR=$(BGFX_DIR)/examples/runtime
BUILD_DIR=${BGFX_DIR}/.build

include $(BGFX_DIR)/scripts/shader.mk
